[package]
name = "datasubway"
version = "0.4.0"
edition = "2024"

[lib]
name = "datasubway"
crate-type = ["rlib"]

[[bin]]
name = "datasubway"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.12.3"
tracing = "0.1"
datafusion = "54.0.0"
parquet = "54"
async-trait = "0.1"

[dev-dependencies]
tempfile = "3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
