[package]
name = "datasubway"
version = "0.3.0"
edition = "2021"

[lib]
name = "datasubway"
crate-type = ["rlib"]

[[bin]]
name = "datasubway"
path = "src/main.rs"

[features]
async = ["dep:tokio", "polars/async"]
dynamic_group_by = ["polars/dynamic_group_by"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
polars = { version = "0.53.0", features = ["lazy", "is_in", "meta", "serde-lazy", "parquet"] }
regex = "1.12.3"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
